/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import static Home.Database.DB_URL;
import static Home.Database.JDBC_DRIVER;
import static Home.Database.PASS;
import static Home.Database.USER;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author HP
 */
public class ResepsionisD extends javax.swing.JFrame {

    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
    public int i;
    Date dNow = new Date();
    SimpleDateFormat dF = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form ResepsionisD
     *
     * @throws java.sql.SQLException
     */
    public ResepsionisD() throws SQLException {
        initComponents();
        koneksi();
        tmplkmr();
    }

    public void koneksi() {
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }

    public void tmplkmr() throws SQLException {
        DefaultTableModel tmplkmr = new DefaultTableModel();
        tmplkmr.addColumn("No. Kamar");
        tmplkmr.addColumn("Tingkat");
        tmplkmr.addColumn("Kondisi");
        tmplkmr.addColumn("Tanggal Masuk");
        tmplkmr.addColumn("Harga");
        Kmr.setModel(tmplkmr);
        try {
            rs = stmt.executeQuery("SELECT * FROM kamar");
            while (rs.next()) {
                tmplkmr.addRow(new Object[]{
                    rs.getString("NoKamar"),
                    rs.getString("Tingkat"),
                    rs.getString("Kondisi"),
                    rs.getString("DateIn"),
                    rs.getString("Harga"),});
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formV = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        pKmrF = new javax.swing.JLabel();
        idV = new javax.swing.JLabel();
        noKmr1 = new javax.swing.JLabel();
        nameF = new javax.swing.JTextField();
        noKmr2 = new javax.swing.JLabel();
        noKmr3 = new javax.swing.JLabel();
        noKmr4 = new javax.swing.JLabel();
        addressF = new javax.swing.JTextField();
        idNF = new javax.swing.JTextField();
        jkC = new javax.swing.JComboBox<>();
        Save = new javax.swing.JButton();
        noKmr5 = new javax.swing.JLabel();
        noKmrF = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        available = new javax.swing.JButton();
        Mainten = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        checkOut = new javax.swing.JButton();
        checkIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Kmr = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        formV.setMinimumSize(new java.awt.Dimension(870, 550));
        formV.getContentPane().setLayout(null);

        pKmrF.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N

        idV.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        idV.setText("No. ID Pengunjung   :");

        noKmr1.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        noKmr1.setText(" Nomor Kamar            :");

        nameF.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N

        noKmr2.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        noKmr2.setText("Alamat Pengunjung   :");

        noKmr3.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        noKmr3.setText("Jenis Kelamin              :");

        noKmr4.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        noKmr4.setText("Nama Pengunjung     :");

        addressF.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        addressF.setPreferredSize(new java.awt.Dimension(10, 29));
        addressF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFActionPerformed(evt);
            }
        });

        idNF.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N

        jkC.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jkC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));

        Save.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        noKmr5.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        noKmr5.setText(" Harga   Kamar            :");

        noKmrF.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(noKmr5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noKmr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pKmrF, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noKmrF, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(793, 793, 793))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idV, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idNF, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(noKmr2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Save)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addressF, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(noKmr3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jkC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(noKmr4)
                                    .addGap(18, 18, 18)
                                    .addComponent(nameF, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(noKmr1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noKmr5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(noKmrF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pKmrF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noKmr4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noKmr2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noKmr3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jkC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Save)
                .addGap(28, 28, 28))
        );

        formV.getContentPane().add(jPanel1);
        jPanel1.setBounds(80, 110, 700, 380);

        jLabel5.setBackground(new java.awt.Color(7, 62, 62));
        jLabel5.setFont(new java.awt.Font("Kaushan Script", 1, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pengisian Data Diri Tamu ");
        formV.getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 860, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Canva - White Table Lamp and Vase on Side Nightstand_RESIZE.jpg"))); // NOI18N
        jLabel4.setMinimumSize(new java.awt.Dimension(720, 480));
        formV.getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 870, 510);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        available.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        available.setText("Available");
        available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableActionPerformed(evt);
            }
        });
        getContentPane().add(available);
        available.setBounds(680, 580, 110, 33);

        Mainten.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        Mainten.setText("Maintenance");
        Mainten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintenActionPerformed(evt);
            }
        });
        getContentPane().add(Mainten);
        Mainten.setBounds(500, 580, 110, 33);

        logOut.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        logOut.setText("Log Out ");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        getContentPane().add(logOut);
        logOut.setBounds(850, 580, 110, 33);

        checkOut.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        checkOut.setText("Check Out");
        checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutActionPerformed(evt);
            }
        });
        getContentPane().add(checkOut);
        checkOut.setBounds(300, 580, 100, 33);

        checkIn.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        checkIn.setText("Check In");
        checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInActionPerformed(evt);
            }
        });
        getContentPane().add(checkIn);
        checkIn.setBounds(90, 580, 90, 33);

        jLabel2.setBackground(new java.awt.Color(7, 62, 62));
        jLabel2.setFont(new java.awt.Font("Kaushan Script", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Kamar Hotel");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 40, 320, 60);

        Kmr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        Kmr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KmrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Kmr);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 140, 760, 400);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Canva - White Table Lamp and Vase on Side Nightstand_RESIZE.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 690);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Canva - White Table Lamp and Vase on Side Nightstand_RESIZE.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KmrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KmrMouseClicked
        i = Kmr.getSelectedRow();
        TableModel model = Kmr.getModel();
        String stats = model.getValueAt(i, 2).toString();
        if ("Available".equals(stats)) {
            Mainten.setVisible(true);
            available.setVisible(false);
        }else if ("Perbaikan".equals(stats)) {
            Mainten.setVisible(false);
            available.setVisible(true);
            checkIn.setVisible(false);
        }

    }//GEN-LAST:event_KmrMouseClicked

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        Homepage h = new Homepage();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logOutActionPerformed

    private void checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutActionPerformed
        TableModel model = Kmr.getModel();
        String stats = (String) model.getValueAt(i, 2);
        String dIn = (String) model.getValueAt(i, 3);
        Date dateIn = null;
        try {
            dateIn = new SimpleDateFormat("yyyy-MM-dd").parse(dIn);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        long dDiff = dNow.getTime() - dateIn.getTime();
        int rDiff = (int) (dDiff / (1000 * 60 * 60 * 24));
        int harga = Integer.parseInt(model.getValueAt(i, 4).toString());
        long total;
        total = rDiff * (long) harga;
        String NoL;
        NoL = (String) model.getValueAt(i, 3) + (String) model.getValueAt(i, 0);
        if ("Digunakan".equals(stats)) {
            int input = JOptionPane.showConfirmDialog(null, "Apakah Tamu sudah membayar ? ", "Konfirmasi Pembayaran",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (input == 0) {
                try {
                    koneksi();
                    stmt.executeUpdate("UPDATE kamar SET Kondisi = 'Available', DateIn = NULL WHERE NoKamar = '" + model.getValueAt(i, 0) + "'");
                    stmt.executeUpdate("UPDATE laporan SET DateOut = '" + dF.format(dNow) + "', Waktu = '" + rDiff + "', Total='" + total + "' WHERE NoLaporan = '" + NoL + "'");
                    JOptionPane.showMessageDialog(null, "OK, perubahan berhasil");
                    tmplkmr();
                } catch (SQLException ex) {
                    System.out.println(ex);
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Mohon maaf kamar ini belum digunakan ");
        }
    }//GEN-LAST:event_checkOutActionPerformed

    private void MaintenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintenActionPerformed
        TableModel model = Kmr.getModel();
        String stats = (String) model.getValueAt(i, 2);
        if ("Available".equals(stats)) {
            try {
                koneksi();
                stmt.executeUpdate("UPDATE kamar SET Kondisi = 'Perbaikan' WHERE NoKamar = '" + model.getValueAt(i, 0) + "'");
                JOptionPane.showMessageDialog(null, "OK, perubahan berhasil");
                tmplkmr();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mohon maaf kamar ini tidak bisa diperbaiki");
        }
    }//GEN-LAST:event_MaintenActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        char JK;
        String noL;
        noL = dF.format(dNow) + noKmrF.getText();
        if ("Laki - Laki".equals((jkC.getItemAt(jkC.getSelectedIndex())))) {
            JK = 'L';
        } else {
            JK = 'P';
        }
        try {
            koneksi();
            stmt.executeUpdate("INSERT INTO visitor VALUES('" + idNF.getText() + "', '" + nameF.getText() + "', '" + addressF.getText() + "', '" + JK + "')");
            stmt.executeUpdate("UPDATE kamar SET Kondisi='Digunakan', DateIn='" + dF.format(dNow) + "' WHERE NoKamar='" + noKmrF.getText() + "'");
            stmt.executeUpdate("INSERT INTO laporan (NoLaporan, NoKamar, NIK, NamaV, Harga, DateIn) VALUE('" + noL + "', '" + noKmrF.getText() + "', '" + idNF.getText() + "', '" + nameF.getText() + "', '" + pKmrF.getText() + "', '" + dF.format(dNow) + "')");
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            formV.setVisible(false);
            tmplkmr();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInActionPerformed
        TableModel model = Kmr.getModel();
        String stats = (String) model.getValueAt(i, 2);
        if ("Available".equals(stats)) {
            formV.setVisible(true);
            noKmrF.setText((String) model.getValueAt(i, 0));
            pKmrF.setText((String) model.getValueAt(i, 4));
        } else {
            JOptionPane.showMessageDialog(null, "Kamar tidak bisa digunakan");
            try {
                koneksi();
                tmplkmr();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_checkInActionPerformed

    private void availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableActionPerformed
        TableModel model = Kmr.getModel();
        String stats = (String) model.getValueAt(i, 2);
        if ("Perbaikan".equals(stats)) {
            try {
                koneksi();
                stmt.executeUpdate("UPDATE kamar SET Kondisi = 'Available' WHERE NoKamar = '" + model.getValueAt(i, 0) + "'");
                JOptionPane.showMessageDialog(null, "OK, perubahan berhasil");
                tmplkmr();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mohon maaf kamar ini tidak bisa diperbaiki");
        }
    }//GEN-LAST:event_availableActionPerformed

    private void addressFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResepsionisD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResepsionisD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResepsionisD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResepsionisD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ResepsionisD().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ResepsionisD.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Kmr;
    private javax.swing.JButton Mainten;
    private javax.swing.JButton Save;
    private javax.swing.JTextField addressF;
    private javax.swing.JButton available;
    private javax.swing.JButton checkIn;
    private javax.swing.JButton checkOut;
    private javax.swing.JFrame formV;
    private javax.swing.JTextField idNF;
    private javax.swing.JLabel idV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jkC;
    private javax.swing.JButton logOut;
    private javax.swing.JTextField nameF;
    private javax.swing.JLabel noKmr1;
    private javax.swing.JLabel noKmr2;
    private javax.swing.JLabel noKmr3;
    private javax.swing.JLabel noKmr4;
    private javax.swing.JLabel noKmr5;
    private javax.swing.JLabel noKmrF;
    private javax.swing.JLabel pKmrF;
    // End of variables declaration//GEN-END:variables
}
